version: '3.8'

services:
  experiments:
    image: pikalab/automl-fairness:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mmagnini:/persistent
    command: >
      sh -c "find experiments/setup -name '*.yml' | 
             xargs -n 1 -P $$(nproc) -I {} poetry run python -m experiments --config {} --output /persistent"

volumes:
  mmagnini:
    external: true
    name: mmagnini
