version: '3.8'

services:
  experiments:
    image: pikalab/automl-fairness:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mmagnini:/home/dev/persistent
    command: >
      chmod 777 run.sh && ./run.sh

volumes:
  mmagnini:
    external: true
    name: mmagnini
